# Generated by Django 5.1 on 2024-08-21 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactBookApi', '0003_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
