# Generated by Django 5.1 on 2024-08-21 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactBookApi', '0004_alter_comment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='average_response_time',
            field=models.CharField(default='1 week', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.CharField(default='default@gmail.com', max_length=100),
            preserve_default=False,
        ),
    ]
